### PR TITLE
Va patch

### PR DESCRIPTION
**Pull request by msuchard**
first 2 of many (?) compatibility issues.

### CODE REVIEW

**Review by schuemie — APPROVED** [review]

**Comment by schuemie** [comment]
You can't merge directly into master, since only new released versions can go into master. If this is not an urgent fix it can go into develop and be included in the next planned release. If it is urgent, we could create a hotfix branch of master, merge this PR into that, and prepare the new hotfix version in the hotfix branch. Once completely ready the hotfix branch could be merged into master and develop.

**Comment by msuchard** [comment]
This code 

```
  metaData <- dplyr::tibble(
    databaseId = databaseId,
    variableField = c(rep('vocabularyVersionCdm', length(vocabularyVersionCdm)),
                      rep('vocabularyVersion', length(vocabularyVersion))),
    valueField = c(vocabularyVersionCdm, vocabularyVersion)
  )
  writeToCsv(data = metaData,
             fileName = "metaData.csv")
```

has been removed in `develop`.   Was this by-design or on-accident?

**Comment by msuchard** [comment]
Another solution (@gowthamrao @schuemie) might be to concatenate the results from this line:

https://github.com/OHDSI/CohortDiagnostics/blob/9ebcff7683239cc9b60da4b2bcefb5237ddc3c4c/R/RunDiagnostics.R#L361

into a _single_ entry (some data sources have *multiple* rows in their `CDM_SOURCE` table)

**Comment by gowthamrao** [comment]
@msuchard  not sure whats going on - can we discuss first 
(Maintainer privilege :) )

**Comment by gowthamrao** [comment]
used an alternate approach for versoin 2.1.1

**Pull request closed without merging**
